Update assemble_hourly_daily.yml

diff --git a/.github/workflows/assemble_hourly_daily.yml b/.github/workflows/assemble_hourly_daily.yml
--- a/.github/workflows/assemble_hourly_daily.yml
+++ b/.github/workflows/assemble_hourly_daily.yml
@@ -43,6 +43,15 @@ jobs:
           git pull
           git add data/hourly/hourly.rds
           git add data/daily/daily.rds
-          git commit -m "Update hourly/daily data set"
-          git push
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          git status | grep modified
+          if [ $? -eq 0 ]
+          then
+            set -e
+            git commit -am "Update hourly/daily data set"
+            git push
+          else
+            set -e
+            echo "No changes since last run"
+          fi
 
